version: '3'
services:
  veloc:
    build:
      context: .
      dockerfile: Dockerfile
    image: veloc
    container_name: veloc
    networks:
      - dokploy-network
    ports:
    - 5000:5000
    
networks:
  dokploy-network:
    external: true
