version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: veloc
    container_name: veloc
    networks:
      - myhost_network
    ports:
    - 80:5000
    
networks:
  myhost_network:
    external: true
